name: Publish Shared Module

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build Shared Module
        run: ./gradlew :shared:build

      - name: Publish to GitHub Packages
        run: ./gradlew :shared:publish
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
